### ISSUE TITLE
ESM? Build errors after updating to v1.3.5

### ISSUE THREAD

**Issue by garth** [remix-run/remix#2691]
### What version of Remix are you using?

1.3.5 and 1.4.0

### Steps to Reproduce

update from 1.3.4 to 1.3.5 or 1.4.0

run `remix build`

### Expected Behavior

App should compile

### Actual Behavior

Lots of errors starting with the following:

```
Building Remix app in production mode...
y-indexeddb is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
The path "encoding" is imported in generated/prisma/client/runtime/index.js but encoding is not listed in your package.json dependencies. Did you forget to install it?
✘ [ERROR] [plugin server-bare-modules] Cannot find module 'encoding/package.json'
Require stack:
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/commands.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/run.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/index.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/index.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli.js
    generated/prisma/client/runtime/index.js:15389:26:
      15389 │         convert = require("encoding").convert;
            ╵                           ~~~~~~~~~~
  This error came from the "onResolve" callback registered here:
    node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:46:12:
      46 │       build.onResolve({
         ╵             ~~~~~~~~~
```

There are many more errors, but all seem realeted.

Reverting back to v1.3.4 and everything is ok again.

**Comment by garth** [comment]
I should also mention that adding the packages (which are not ESM only) to the serverDependenciesToBundle list does not make any difference.

**Comment by DAlperin** [comment]
> Reverting back to v1.3.4 and everything is ok again.

Can confirm that downgrading worked for me as well as several others in the discord. From what I can tell by a quick glance through the commit merging 1.3.5 it seems like it makes some significant changes to the compiler in the remix-dev package, can't pinpoint what the problem is specifically yet.

**Comment by ivosabev** [comment]
Same here with fontawesome pro

```
[ERROR] [plugin server-bare-modules] Cannot find module '/Users/User/remix/node_modules/@fortawesome/pro-solid-svg-icons/package.json.js'
```

It adds `.js` when it should just look for `package.json`

**Comment by mcansh** [comment]
@ivosabev what does the fortawesome pro package.json look like in terms of `"type"` and `"exports"`?

**Comment by zayenz** [comment]
Similar issue for me with importing Headless UI into a Remix Blues stack app. After upgrading to 1.3.5 from 1.3.4 I get the following types of errors:

```
$ npm run build

[... snip ...]

✘ [ERROR] [plugin server-bare-modules] Package subpath './package.json' is not defined by "exports" in /Users/zayenz/remix-app/node_modules/@headlessui/react/package.json

    node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:125:32:
      125 │   let packageJsonFile = require.resolve(`${packageName}/package.j...
          ╵                                 ^

    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:433:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:712:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at warnOnceIfEsmOnlyPackage (/Users/zayenz/remix-app/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:125:33)
    at /Users/zayenz/remix-app/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:95:11
    at callback (/Users/zayenz/remix-app/@remix-run/dev/node_modules/esbuild/lib/main.js:920:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handleRequest (/Users/zayenz/remix-app/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:700:30)

  This error came from the "onResolve" callback registered here:

    node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:46:12:
      46 │       build.onResolve({
         ╵             ~~~~~~~~~

    at setup (/Users/zayenz/remix-app/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:46:13)
    at handlePlugins (/Users/zayenz/remix-app/node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:842:23)

  The plugin "server-bare-modules" was triggered by this import

    route:/Users/zayenz/remix-app/app/routes/index.tsx:4:45:
      4 │ import { Disclosure, Menu, Transition } from "@headlessui/react";
        ╵                                              ~~~~~~~~~~~~~~~~~~~
```

**Comment by mcansh** [comment]
good news, i think #2694 should cover these bases

**Comment by ivosabev** [comment]
### @fortawesome/pro-solid-svg-icons/package.json

```
{
  "description": "The iconic font, CSS, and SVG framework",
  "keywords": [
    "font",
    "awesome",
    "fontawesome",
    "icon",
    "svg",
    "bootstrap"
  ],
  "homepage": "https://fontawesome.com",
  "bugs": {
    "url": "https://github.com/FortAwesome/Font-Awesome/issues"
  },
  "author": "The Font Awesome Team (https://github.com/orgs/FortAwesome/people)",
  "repository": {
    "type": "git",
    "url": "https://github.com/FortAwesome/Font-Awesome"
  },
  "engines": {
    "node": ">=6"
  },
  "dependencies": {
    "@fortawesome/fontawesome-common-types": "6.1.1"
  },
  "version": "6.1.1",
  "name": "@fortawesome/pro-solid-svg-icons",
  "main": "index.js",
  "module": "index.es.js",
  "jsnext:main": "index.es.js",
  "license": "UNLICENSED",
  "types": "./index.d.ts",
  "sideEffects": false,
  "exports": {
    ".": {
      "import": "./index.es.js",
      "require": "./index.js",
      "default": "./index.js"
    },
    "./index": {
      "import": "./index.es.js",
      "require": "./index.js",
      "default": "./index.js"
    },
    "./index.js": {
      "import": "./index.es.js",
      "require": "./index.js",
      "default": "./index.js"
    },
    "./*": "./*.js"
  },
  "scripts": {
    "postinstall": "node attribution.js"
  }
}
```

@mcansh

**Comment by ivosabev** [comment]
Thanks for the quick fix!

**Comment by mcansh** [comment]
> i will cut an experimental soon

sorry all, forgot to do this, i just cut `v0.0.0-experimental-9aba8b51` which has this in there :)

**Comment by ianduvall** [comment]
Looks like `server-bare-modules` in `v0.0.0-experimental-9aba8b51` is failing to find `@heroicons/react`.

> ✘ [ERROR] [plugin server-bare-modules] Cannot find module '@heroicons/react'

```
  This error came from the "onResolve" callback registered here:

    node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:47:12:
      47 │       build.onResolve({
         ╵             ~~~~~~~~~

    at setup (removed/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:47:13)
    at handlePlugins (removed/node_modules/esbuild/lib/main.js:842:23)
```

Here's a [repo](https://github.com/ianduvall/remix-test-1.3.5) to reproduce the issue (it's the Indie Stack with `@heroicons/react` added).

**Comment by mailok** [comment]
Looks like `v0.0.0-experimental-9aba8b51` is failing also in `@headlessui/react`
If it helps at all, these are the my dependencies:

```
  "dependencies": {
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@fortawesome/react-fontawesome": "^0.1.18",
    "@headlessui/react": "^1.5.0",
    "@prisma/client": "^3.12.0",
    "@remix-run/react": "0.0.0-experimental-9aba8b51",
    "@remix-run/serve": "0.0.0-experimental-9aba8b51",
    "@remix-run/server-runtime": "0.0.0-experimental-9aba8b51",
    "@remix-run/vercel": "0.0.0-experimental-9aba8b51",
    "accept-language-parser": "^1.5.0",
    "bcryptjs": "^2.4.3",
    "i18next": "^21.6.16",
    "i18next-http-backend": "^1.4.0",
    "js-cookie": "^3.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-i18next": "^11.16.5",
    "react-icons": "^4.3.1",
    "remix": "0.0.0-experimental-9aba8b51"
  },
```

**Comment by mcansh** [comment]
> Looks like `v0.0.0-experimental-9aba8b51` is failing also in `@headlessui/react`

weird, my screenshot above has headlessui working, I'll take another look!

**Comment by mcansh** [comment]
> Looks like `server-bare-modules` in `v0.0.0-experimental-9aba8b51` is failing to find `@heroicons/react`

this appears to be a slightly different issue, each sub import (solid/outline) have their own package.json with _no_ information in them [https://github.com/tailwindlabs/heroicons/blob/master/scripts/build.js#L112-L113](https://github.com/tailwindlabs/heroicons/blob/master/scripts/build.js#L112-L113) I'll see if we can make something work 🥴

**Comment by machour** [comment]
@mcansh please cut us a new experimental release when you have time so that we can validate the fix and ship it in 1.3.6 🙏

**Comment by mcansh** [comment]
> @mcansh please cut us a new experimental release when you have time so that we can validate the fix and ship it in 1.3.6 🙏

`v0.0.0-experimental-a04f3d18` is on the way https://github.com/remix-run/remix/runs/5998229731?check_suite_focus=true

**Comment by mcansh** [comment]
here's heroicons being used 
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/11698668/163062592-26c44342-85fc-4b14-b6a7-bf23179d9567.png">

and a build not exploding 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/11698668/163062659-8074edf0-b617-42ac-9853-867a0ac3a6d6.png">

**Comment by machour** [comment]
I can confirm that `v0.0.0-experimental-a04f3d18` fixes all my issues 🎉 

@mailok @ianduvall would you mind giving this a try?

**Comment by garth** [comment]
I've just tested with `v0.0.0-experimental-a04f3d18`, though there are a lot less than before, I still have build errors:

```
Building Remix app in production mode...
@hocuspocus/server is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
@hocuspocus/extension-logger is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
@hocuspocus/extension-monitor is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
@hocuspocus/extension-rocksdb is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
@hocuspocus/provider is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
y-indexeddb is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
The path "encoding" is imported in generated/prisma/client/runtime/index.js but encoding is not listed in your package.json dependencies. Did you forget to install it?
▲ [WARNING] Comparison with -0 using the "===" operator will also match 0
    generated/prisma/client/runtime/index.js:13474:29:
      13474 │             } else if (x === -0) {
            ╵                              ~~
  Floating-point equality is defined such that 0 and -0 are equal, so "x === -0" returns true for both 0 and -0. You need to use "Object.is(x, -0)" instead to test for -0.
✘ [ERROR] [plugin server-bare-modules] Cannot find module 'encoding'
Require stack:
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/commands.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/run.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/index.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/index.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli.js
    generated/prisma/client/runtime/index.js:15389:26:
      15389 │         convert = require("encoding").convert;
            ╵                           ~~~~~~~~~~
  This error came from the "onResolve" callback registered here:
    node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:47:12:
      47 │       build.onResolve({
         ╵             ~~~~~~~~~
    at setup (/node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:47:13)
    at handlePlugins (/node_modules/.pnpm/esbuild@0.14.22/node_modules/esbuild/lib/main.js:842:23)
Build failed with 1 error:
generated/prisma/client/runtime/index.js:15389:26: ERROR: [plugin: server-bare-modules] Cannot find module 'encoding'
Require stack:
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/commands.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/run.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/index.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/index.js
- /node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli.js
Error
    at Object.onBuildFailure (/node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/commands.js:150:13)
    at buildEverything (/node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler.js:280:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.build (/node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler.js:105:3)
    at async Object.build (/node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/commands.js:145:3)
    at async Object.run (/node_modules/.pnpm/@remix-run+dev@0.0.0-experimental-a04f3d18_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/run.js:467:7)
```

**Comment by mcansh** [comment]
it appears that "encoding" is not installed 🤔 - installing it seems like a workaround, as they have a try/catch for it in usage, but if you want to use that experimental (or 1.4.0-pre.0) that should be sufficient until i can see what's up :)

**Comment by garth** [comment]
Unfortunately v1.4 still has the same issue. I am travelling for Easter, but will try to make a reproduction when I return. Please leave this issue open.

**Comment by machour** [comment]
@garth is the issue related to `encoding` from Prisma? Safe travels!

**Comment by garth** [comment]
Yes, it seems to originate from prisma, but when I revert remix back to v1.3.4 there are no build errors.

**Comment by garth** [comment]
Not sure if it's helpful, but these are my dependencies:

```json
 "dependencies": {
    "@headlessui/react": "^1.5.0",
    "@heroicons/react": "^1.0.6",
    "@hocuspocus/extension-logger": "^1.0.0-alpha.76",
    "@hocuspocus/extension-monitor": "^1.0.0-alpha.103",
    "@hocuspocus/extension-rocksdb": "^1.0.0-alpha.103",
    "@hocuspocus/provider": "^1.0.0-alpha.36",
    "@hocuspocus/server": "^1.0.0-alpha.102",
    "@prisma/client": "^3.12.0",
    "@react-spring/web": "^9.4.4",
    "@remix-run/express": "1.4.0",
    "@remix-run/node": "1.4.0",
    "@remix-run/react": "1.4.0",
    "@syncedstore/core": "^0.3.7",
    "@syncedstore/react": "^0.3.5",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.5.0",
    "@tailwindcss/typography": "^0.5.2",
    "@tiptap/core": "^2.0.0-beta.174",
    "@tiptap/extension-blockquote": "^2.0.0-beta.26",
    "@tiptap/extension-bold": "^2.0.0-beta.26",
    "@tiptap/extension-bullet-list": "^2.0.0-beta.26",
    "@tiptap/extension-collaboration": "^2.0.0-beta.33",
    "@tiptap/extension-collaboration-cursor": "^2.0.0-beta.34",
    "@tiptap/extension-document": "^2.0.0-beta.15",
    "@tiptap/extension-dropcursor": "^2.0.0-beta.25",
    "@tiptap/extension-gapcursor": "^2.0.0-beta.34",
    "@tiptap/extension-heading": "^2.0.0-beta.26",
    "@tiptap/extension-italic": "^2.0.0-beta.26",
    "@tiptap/extension-list-item": "^2.0.0-beta.20",
    "@tiptap/extension-ordered-list": "^2.0.0-beta.27",
    "@tiptap/extension-paragraph": "^2.0.0-beta.23",
    "@tiptap/extension-superscript": "^2.0.0-beta.10",
    "@tiptap/extension-text": "^2.0.0-beta.15",
    "@tiptap/extension-text-align": "^2.0.0-beta.29",
    "@tiptap/extension-underline": "^2.0.0-beta.23",
    "@tiptap/react": "^2.0.0-beta.108",
    "bufferutil": "^4.0.6",
    "classnames": "^2.3.1",
    "compression": "^1.7.4",
    "date-fns": "^2.28.0",
    "dotenv": "^16.0.0",
    "express": "^4.17.3",
    "fuse.js": "^6.5.3",
    "jsonwebtoken": "^8.5.1",
    "morgan": "^1.10.0",
    "nanoid": "^3.3.2",
    "nodemailer": "^6.7.3",
    "plausible-tracker": "^0.3.5",
    "postcss": "^8.4.12",
    "prosemirror-model": "^1.16.1",
    "prosemirror-state": "^1.3.4",
    "prosemirror-view": "^1.23.12",
    "qrcode.react": "^3.0.1",
    "react": "^17.0.2",
    "react-copy-to-clipboard": "^5.1.0",
    "react-dom": "^17.0.2",
    "react-hot-toast": "^2.2.0",
    "react-swipeable": "^6.2.1",
    "tailwindcss": "^3.0.24",
    "validator": "^13.7.0",
    "ws": "^8.5.0",
    "y-indexeddb": "^9.0.7",
    "y-protocols": "^1.0.5",
    "y-richtext-viewer": "^0.5.2",
    "yjs": "^13.5.34"
  },
  "devDependencies": {
    "@remix-run/dev": "1.4.0",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react-hooks": "^7.0.2",
    "@types/compression": "^1.7.2",
    "@types/express": "^4.17.13",
    "@types/jsonwebtoken": "^8.5.8",
    "@types/morgan": "^1.9.3",
    "@types/nodemailer": "^6.4.4",
    "@types/qrcode.react": "^1.0.2",
    "@types/react": "^17.0.44",
    "@types/react-copy-to-clipboard": "^5.0.2",
    "@types/react-dom": "^17.0.15",
    "@types/tailwindcss": "^3.0.10",
    "@types/validator": "^13.7.2",
    "@typescript-eslint/eslint-plugin": "^5.19.0",
    "@typescript-eslint/parser": "^5.19.0",
    "@vitejs/plugin-react": "^1.3.1",
    "autoprefixer": "^10.4.4",
    "concurrently": "^7.1.0",
    "csstype": "^3.0.11",
    "cypress": "^9.5.4",
    "esbuild": "^0.14.36",
    "eslint": "^8.13.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-hooks": "^4.4.0",
    "happy-dom": "^2.55.0",
    "nodemon": "^2.0.15",
    "prettier": "^2.6.2",
    "prettier-plugin-tailwindcss": "^0.1.8",
    "prisma": "^3.12.0",
    "rimraf": "^3.0.2",
    "typescript": "~4.6.3",
    "vite": "^2.9.5",
    "vite-tsconfig-paths": "^3.4.1",
    "vitest": "^0.9.3"
  },
```

**Comment by mcansh** [comment]
experimental coming up!

**Comment by garth** [comment]
@mcansh Looking good! The build runs now. I still have some ESM package warnings I didn't have before, but maybe they are genuine, so I will investigate those further.

**Comment by garth** [comment]
So it's building now, but with a couple of warnings still.

I have added all packages that had ESM warnings to `serverDependenciesToBundle`, but `lib0` is still shows a warning even after being added. And the `encoding` dependency warning is still there. Also some of the dependencies are client side only but I added them all to clear the warnings (eg `y-indexeddb`).

```js
  serverDependenciesToBundle: [
    '@hocuspocus/server',
    '@hocuspocus/extension-logger',
    '@hocuspocus/extension-monitor',
    '@hocuspocus/extension-rocksdb',
    '@hocuspocus/common',
    '@hocuspocus/provider',
    'y-indexeddb',
    'lib0',
  ],
```

```
lib0 is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
The path "encoding" is imported in generated/prisma/client/runtime/index.js but encoding is not listed in your package.json dependencies. Did you forget to install it?
```

But if I ignore these warnings the app seems to run fine and all tests are green.

Just to be sure it wasn't anything in my tsconfig, I took the latest tsconfig from `pnpx create-remix --template remix-run/indie-stack blog-tutorial`, but that didn't change anything.

**Comment by machour** [comment]
@garth I allowed myself to revert the title change so that users revisiting this issue in the future are not confused, as most issues described were fixed in 1.4.0

Ideally we'd open a new issue to track 1.4.0 problems, but that's not really required here since we're almost done :)

**Comment by garth** [comment]
Spent a bit more time on this today. I think the last remaining warnings are related to pnpm not hoisting packages.

Adding lib0 (which is required by yjs) with a regex `/lib0/` instead of `'lib0'` in serverDependenciesToBundle and adding a top level dependency on `'encoding'` (which is required by prisma) seems to have fixed the remaining issues.

Whilst I'm happy to have this working again, I'm not entirely convinced about the DX around the changes that came in with v1.3.4. Why would everything have worked just fine before not after?

Thanks for you help in investigating this @machour and @mcansh. I went back and checked if v1.4.0 would work after my latest config updates, but it seems that the changes you made for v0.0.0-experimental-aaac29de are still required, so I will stick with this version until they get merged.

**Comment by mcansh** [comment]
we made some changes to help users more easily detect which packages to add to serverDependenciesToBundle, but unfortunately that came with a bunch of added complexity and causes some things to break, i think we’ll rollback the changes there
