### PR TITLE
feat: replace node-fetch with @remix-run/web-fetch

### PR DESCRIPTION
**Pull request by jacob-ebey**
This PR replaces the internal usage of `node-fetch` with `@remix-run/web-fetch` to be more spec compliant and allow for ReadableStream's to be used as a body in node.

This work is critical to enable a runtime agnostic way to implement streaming in the server-runtime package and provide React 18 support to everyone.

I have also re-worked the file upload handler API to operate on an AsyncIterable<Uint8Array> for the body content. This allows for better error propagation as well as bringing `unstable_parseMultipartFormData` to all supported platforms, not just Node.

- [x] Docs
- [x] Tests

### CODE REVIEW

File: packages/remix-architect/server.ts [hunk 1]
```diff
@@ -53,10 +49,10 @@ export function createRequestHandler({
     let loadContext =
       typeof getLoadContext === "function" ? getLoadContext(event) : undefined;
 
-    let response = (await handleRequest(
+    let response = await handleRequest(
       request as unknown as Request,
       loadContext
-    )) as unknown as NodeResponse;
```
Comment (mjackson) [inline packages/remix-architect/server.ts:59]: Let's keep using node types in this file (and in all node adapters) if we can.

File: packages/remix-express/package.json [hunk 2]
```diff
@@ -15,6 +15,7 @@
     "@remix-run/node": "1.4.2"
   },
   "peerDependencies": {
+    "@remix-run/web-stream": "^1.0.2",
```
Comment (mjackson) [inline packages/remix-express/package.json:18]: This should probably be a regular dep.

File: packages/remix-express/server.ts [hunk 3]
```diff
@@ -133,11 +145,27 @@ export function sendRemixResponse(
     res.set("Connection", "close");
   }
 
-  if (Buffer.isBuffer(nodeResponse.body)) {
-    res.end(nodeResponse.body);
-  } else if (nodeResponse.body?.pipe) {
-    nodeResponse.body.pipe(res);
+  if (nodeResponse.body) {
```
Comment (mjackson) [inline packages/remix-express/server.ts:148]: Add a `pipeReadableStreamToNodeReadable(readableStream, nodeReadable)` util (?)

File: packages/remix-express/server.ts [hunk 4]
```diff
@@ -109,21 +110,32 @@ export function createRemixRequest(
   };
 
   if (req.method !== "GET" && req.method !== "HEAD") {
-    init.body = req.pipe(new PassThrough({ highWaterMark: 16384 }));
+    init.body = new ReadableStream({
```
Comment (mjackson) [inline packages/remix-express/server.ts:113]: Add `createReadableStreamFromNodeReadable(nodeReadable)` util ?

File: packages/remix-node/__tests__/parseMultipartFormData-test.ts [hunk 5]
```diff
@@ -1,7 +1,8 @@
-import { Blob, File } from "@web-std/file";
+import { FormData as NodeFormData } from "@remix-run/web-fetch";
+import { Blob, File } from "@remix-run/web-file";
 
 import { Request as NodeRequest } from "../fetch";
-import { FormData as NodeFormData } from "../formData";
+// import { FormData as NodeFormData } from "../formData";
```
Comment (mjackson) [inline packages/remix-node/__tests__/parseMultipartFormData-test.ts:5]: Remove

File: packages/remix-node/__tests__/parseMultipartFormData-test.ts [hunk 6]
```diff
@@ -19,8 +20,8 @@ describe("internalParseFormData", () => {
 
     let uploadHandler = createMemoryUploadHandler({});
     let parsedFormData = await internalParseFormData(
-      req.headers.get("Content-Type"),
-      req.body as any,
+      req,
+      req.formData.bind(req),
```
Comment (mjackson) [inline packages/remix-node/__tests__/parseMultipartFormData-test.ts:24]: Remove this param and use req.formData() method.

File: packages/remix-node/fetch.ts [hunk 7]
```diff
@@ -95,8 +31,8 @@ class NodeRequest extends BaseNodeRequest {
         /multipart\/form-data/.test(contentType))
     ) {
       return await internalParseFormData(
-        contentType,
-        this.body as Readable,
+        this,
+        super.formData.bind(this),
```
Comment (mjackson) [inline packages/remix-node/fetch.ts:35]: Can simplify here as well.

File: packages/remix-node/fetch.ts [hunk 8]
```diff
@@ -111,29 +47,3 @@ class NodeRequest extends BaseNodeRequest {
...
-  init = { compress: false, ...init };
-
-  if (init?.body instanceof NodeFormData) {
-    init = {
-      ...init,
-      body: formDataToStream(init.body),
-    };
-  }
-
-  // Default to { compress: false } so responses can be proxied through more
```
Comment (mjackson) [inline packages/remix-node/fetch.ts:135]: TODO: Double check that web-std/fetch doesn't decompress the bytes in a response so you can return a fetch() for an encoded resource directly from your loader().

File: packages/remix-node/index.ts [hunk 9]
```diff
@@ -5,10 +5,10 @@ sourceMapSupport.install();
 export { AbortController } from "abort-controller";
 
 export type {
-  HeadersInit,
-  RequestInfo,
+  // HeadersInit,
+  // RequestInfo,
   RequestInit,
-  ResponseInit,
+  // ResponseInit,
```
Comment (mjackson) [inline packages/remix-node/index.ts:11]: Let's try and keep these exports if we can, even though they are really just re-exports of global DOM types, so we don't have a breaking change here.

**Review by mjackson — CHANGES_REQUESTED** [review]
Great start. Keep going! Let's also look into getting rid of busboy and using our own multipart parser in web-std/form-data.

**Review by mjackson — CHANGES_REQUESTED** [review]

File: packages/remix-node/upload/fileUploadHandler.ts [hunk 10]
```diff
@@ -159,14 +158,43 @@ export class NodeOnDiskFile implements File {
...
+    }
+
+    let stats = statSync(this.filepath);
+    return stats.size;
+  }
+
+  slice(start?: number, end?: number, type?: string): Blob {
+    let startOffset = this.slicer?.start || 0;
+
+    start = startOffset + (start || 0);
```
[the remark this answers is not in the document]
Comment (jacob-ebey) [reply packages/remix-node/upload/fileUploadHandler.ts:179]: The `stream-slice` library takes care of this for us. I've added some tests though.

File: packages/remix-node/upload/fileUploadHandler.ts [hunk 11]
```diff
@@ -159,14 +158,43 @@ export class NodeOnDiskFile implements File {
...
+    end = startOffset + (end || this.size);
```
[the remark this answers is not in the document]
Comment (jacob-ebey) [reply packages/remix-node/upload/fileUploadHandler.ts:180]: Didn't need Math.min but I did update the size getter to properly reflect the slice.

File: examples/file-and-cloudinary-upload/app/utils/utils.server.ts [hunk 12]
```diff
@@ -1,27 +1,44 @@
...
       (error, result) => {
         if (error) {
           reject(error);
+          return;
         }
         resolve(result);
       }
     );
-    fileStream.pipe(uploadStream);
+    dataStream.pipe(uploadStream);
```
Comment (mjackson) [inline examples/file-and-cloudinary-upload/app/utils/utils.server.ts:25]: Update to use `writeAsyncIterableToWritable(part.data, uploadStream)`.

File: packages/remix-node/stream.ts [hunk 13]
```diff
@@ -0,0 +1,196 @@
+import type { Writable } from "stream";
+import { Stream } from "stream";
+
+const { readableHighWaterMark } = new Stream.Readable();
+
+export async function pipeReadableStreamToWritable(
```
Comment (mjackson) [inline packages/remix-node/stream.ts:6]: Let's implement these APIs in here.

```
  await writeReadableStreamToWritable(request.body, nodeWritable);
  await writeAsyncIterableToWritable(part.data, nodeWritable);
  
  const webReadableStream = createReadableStreamFromReadable(nodeReadable);
```

File: packages/remix-node/stream.ts [hunk 14]
```diff
@@ -0,0 +1,196 @@
...
+
+    await read();
+  }
+
+  await read();
+
+  return Buffer.concat(chunks).toString("base64");
+}
+
+export async function readableStreamToString(stream: ReadableStream<any>) {
```
Comment (mjackson) [inline packages/remix-node/stream.ts:49]: Add optional `encoding` arg for the `buffer.toString(encoding)` and just have one function instead of 2 (get rid of `readableStreamToBase64String`)

File: packages/remix-node/stream.ts [hunk 15]
```diff
@@ -0,0 +1,196 @@
...
+
+    await read();
+  }
+
+  await read();
+
+  return Buffer.concat(chunks).toString();
+}
+
+export const readableStreamFromStream = (
```
Comment (mjackson) [inline packages/remix-node/stream.ts:70]: Rename to `createReadableStreamFromReadable`.

File: packages/remix-node/stream.ts [hunk 16]
```diff
@@ -0,0 +1,196 @@
...
+  source: Stream & { readableHighWaterMark?: number }
```
Comment (mjackson) [inline packages/remix-node/stream.ts:71]: This type should be `Readable`

File: packages/remix-node/stream.ts [hunk 17]
```diff
@@ -0,0 +1,196 @@
...
+      writable.end();
+      return;
+    }
+
+    writable.write(value);
+
+    await read();
+  }
+
+  await read();
```
Comment (mjackson) [inline packages/remix-node/stream.ts:25]: try/catch this and propagate the error through to the writable?

File: packages/remix-node/stream.ts (hunk 14 above)
Comment (mjackson) [reply packages/remix-node/stream.ts:49]: maybe this belongs in server-runtime? but it can't use Buffer if it is.

**Review by mjackson — CHANGES_REQUESTED** [review]

File: packages/remix-node/magicExports/remix.ts [hunk 18]
```diff
@@ -13,4 +13,4 @@ export {
   unstable_parseMultipartFormData,
 } from "@remix-run/node";
 
-export type { UploadHandler, UploadHandlerArgs } from "@remix-run/node";
+export type { UploadHandler, UploadHandlerPart } from "@remix-run/node";
```
Comment (MichaelDeBoey) [inline packages/remix-node/magicExports/remix.ts:16]: We should also keep `UploadHandlerArgs` here, as it would otherwise be a breaking change

```suggestion
export type { UploadHandler, UploadHandlerArgs, UploadHandlerPart } from "@remix-run/node";
```

File: packages/remix-node/index.ts [hunk 19]
```diff
@@ -76,4 +79,8 @@ export type {
   SessionData,
   SessionIdStorageStrategy,
   SessionStorage,
+  UploadHandlerPart,
+  UploadHandler,
```
Comment (MichaelDeBoey) [inline packages/remix-node/index.ts:83]: `@remix-run/server-runtime` should also export it

```suggestion
  UploadHandler,
  UploadHandlerArgs,
```

**Review by MichaelDeBoey — CHANGES_REQUESTED** [review]

File: packages/remix-node/magicExports/remix.ts (hunk 18 above)
Comment (jacob-ebey) [reply packages/remix-node/magicExports/remix.ts:16]: It's a breaking change anyways as the props on the type have changed. Upload handlers are unstable so this should be fine.

File: packages/remix-server-runtime/data.ts [hunk 20]
```diff
@@ -33,7 +33,7 @@ export async function callRouteAction({
   let result;
   try {
     result = await action({
-      request: stripDataParam(stripIndexParam(request)),
+      request: stripDataParam(stripIndexParam(request.clone())),
```
[the remark this answers is not in the document]
Comment (jacob-ebey) [reply packages/remix-server-runtime/data.ts:36]: After talking with @mcansh it seems we want to keep this. It was only removed due to an issue in the old fetch polyfill.

File: packages/remix-node/stream.ts (hunk 14 above)
Comment (jacob-ebey) [reply packages/remix-node/stream.ts]: I'm going to say it should stay. Using the native Buffer is going to be significantly faster than doing this ourselves in userland.

File: packages/remix-server-runtime/__tests__/formData-test.ts [hunk 21]
```diff
@@ -0,0 +1,175 @@
...
+      let formData = new NodeFormData();
+      formData.set("a", "value");
+      formData.set("blob", new Blob(["blob".repeat(1000)]), "blob.txt");
+      formData.set("file", new File(["file".repeat(1000)], "file.txt"));
+
+      let underlyingRequest = new NodeRequest("https://test.com", {
+        method: "post",
+        body: formData,
+      });
+      let underlyingBody = await underlyingRequest.text();
```
Comment (mjackson) [inline packages/remix-server-runtime/__tests__/formData-test.ts:104]: Are you running this through a `new Request` just so you can get a URL-encoded string out? Because if you are you can just use `new URLSearchParams(formData).toString()` to get the same thing.

File: packages/remix-server-runtime/__tests__/formData-test.ts [hunk 22]
```diff
@@ -0,0 +1,175 @@
...
```
Comment (mjackson) [inline packages/remix-server-runtime/__tests__/formData-test.ts:144]: Same question as above. Could possibly simplify this code using `URLSearchParams`.

**Review by mjackson — CHANGES_REQUESTED** [review]

File: packages/remix-server-runtime/__tests__/formData-test.ts (hunk 21 above)
Comment (jacob-ebey) [reply packages/remix-server-runtime/__tests__/formData-test.ts:104]: It's actually a multipart formdata body. It's to test what happens when things are interrupted.

File: packages/remix-node/tsconfig.json [hunk 23]
```diff
@@ -1,7 +1,7 @@
 {
   "exclude": ["__tests__"],
   "compilerOptions": {
-    "lib": ["ES2019", "DOM.Iterable"],
+    "lib": ["ES2019", "DOM", "DOM.Iterable"],
```
[the remark this answers is not in the document]
Comment (jacob-ebey) [reply packages/remix-node/tsconfig.json:4]: Aren't needed. Leftover from me playing with stuff.

**Review by mjackson — APPROVED** [review]
LGTM!

**Comment by dahlbyk** [comment]
Any obvious reason I'd be getting this after upgrading from 1.4? If not, I'll try to submit a repro or fix.

```text
TypeError: this._readableStream.getReader is not a function
    at ReadableStreamSearch.[Symbol.asyncIterator] ({redacted}/node_modules/@web3-storage/multipart-parser/cjs/src/search.js:149:41)
    at AsyncGenerator.next (<anonymous>)
    at Object.streamMultipart ({redacted}/node_modules/@web3-storage/multipart-parser/cjs/src/index.js:119:29)
    at streamMultipart.next (<anonymous>)
    at parseMultipartFormData ({redacted}/node_modules/@remix-run/server-runtime/formData.js:48:18)
```
