### PR TITLE
chore(remix-dev): remove `jsxDev` compiler option

### LINKED ISSUE #4081: import_jsx_dev_runtime.jsxDEV is not a function after upgrade to 1.7.0 in Docker Container
### What version of Remix are you using?

1.7.0

### Steps to Reproduce

After upgrading to 1.7.0 and building my docker container, Going to any page yields `import_jsx_dev_runtime.jsxDEV is not a function` on the server, and an error page is rendered.

Here is my Docker file that causes it to fail:
```
# Base Node image
FROM node:lts-alpine as base

# Setup all node_modules
FROM base as deps

RUN mkdir /app
WORKDIR /app

ADD package.json ./
ADD yarn.lock ./
RUN yarn install --production=false

# Setup production node_modules
FROM base as production-deps

RUN mkdir /app
WORKDIR /app

COPY --from=deps /app/node_modules /app/node_modules
ADD package*.json ./

# Build the app
FROM base as build

ENV NODE_ENV=production

RUN mkdir /app
WORKDIR /app

COPY --from=deps /app/node_modules /app/node_modules

ADD . .
RUN yarn run build

# Build production image
FROM base

RUN mkdir /app
WORKDIR /app

COPY --from=production-deps /app/node_modules /app/node_modules

COPY --from=build /app/build /app/build
COPY --from=build /app/public /app/public
ADD . .

EXPOSE 3000

CMD ["yarn", "start"]
```

It is only failing in the container, running the app even with remix-serve works correctly. All package.json dependencies are locked in.

### Expected Behavior

The app should work as it did before the upgrade to 1.7.0 (Release notes said no changes to code necessary).

### Actual Behavior

The app fails to render any pages.

### LINKED ISSUE #5743: TypeError: (0 , import_jsx_dev_runtime.jsxDEV) is not a function
### What version of Remix are you using?

1.14.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```diff
    "dev": "run-p dev:*",
+    "dev:build": "cross-env NODE_ENV=development remix dev",
+    "dev:serve": "cross-env NODE_ENV=development nodemon --watch build server.js",
-    "dev:server": "cross-env NODE_ENV=development node --inspect --require ./node_modules/dotenv/config --require ./mocks ./build/server.js",
-    "dev:build": "cross-env NODE_ENV=development npm run build:server -- --watch",
-    "dev:remix": "cross-env NODE_ENV=development remix watch",
    "dev:css": "cross-env NODE_ENV=development npm run generate:css -- --watch",
```

### Expected Behavior

HMR is working without errors

### Actual Behavior

Getting this error:
```
TypeError: (0 , import_jsx_dev_runtime.jsxDEV) is not a function
    at /Users//Projects//app/entry.server.tsx:64:9
    at new Promise (<anonymous>)
    at handleRequest (/Users//Projects//app/entry.server.tsx:59:10)
    at handleDocumentRequestRR (/Users//Projects//build/server.js:38925:18)
    at requestHandler (/Users//Projects//build/server.js:38787:22)
    at /Users//Projects//build/server.js:39945:26
```

### PR DESCRIPTION
**Pull request by mcansh**
it causes `import_jsx_dev_runtime.jsxDEV is not a function` errors when building prior to dev mode

Closes #4081
Closes #5743

- [ ] Docs
- [ ] Tests

Testing Strategy:

### CODE REVIEW

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by kyeotic** [comment]
Is this still planned @mcansh

**Comment by lukaszdz** [comment]
Bumping this, this error blows up my app when I deploy it to fly.io. Happens on a fresh install and fresh deploy of this PWA remix stack - https://github.com/ShafSpecs/rockspec-stack

**Comment by sajidmasoodbscs** [comment]
Is this still planned @mcansh? I'm facing still the same issue "import_jsx_dev_runtime.jsxDEV is not a function"  on local when try to start with npm start,  but when use "npm run dev" error not produced.

**Comment by pcattori** [comment]
This error is caused when a Remix app is built in dev mode and subsequently started by an app server running in production:

```sh
# 1. build app in dev mode
NODE_ENV=development remix build # either like this,
remix dev # or like this

# 2. later, without rebuilding for prod, run the app with a production-mode app server
NODE_ENV=production remix-serve # either like this,
NODE_ENV=production node ./server.js # or like this
```

In CI/CD, your app should be getting built and run in production-mode only and shouldn't be a problem.

For local dev, the solution is to infer the mode from the built Remix server, which is solved by #6964, making this PR obsolete.
