### ISSUE TITLE
Weird undebuggable error when upgrading from 2.4.0 to 2.4.1

### ISSUE THREAD

**Issue by ivosabev** [remix-run/remix#8433]
### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 79.17 MB / 16.00 GB
    Shell: 5.2.21 - /opt/homebrew/bin/bash
Binaries:
    Node: 18.18.2 - ~/.n/bin/node
    npm: 10.2.5 - ~/.n/bin/npm
Browsers:
    Chrome: 120.0.6099.199
    Safari: 17.2.1
npmPackages:
    @remix-run/dev: 2.4.1 => 2.4.1 
    @remix-run/express: 2.4.1 => 2.4.1 
    @remix-run/node: 2.4.1 => 2.4.1 
    @remix-run/react: 2.4.1 => 2.4.1 
    vite: 5.0.10 => 5.0.10
```

### Used Package Manager

npm

### Expected Behavior

Nothing works.

### Actual Behavior

I get this vite error, I am runing the unstable-vite-express template, I've removed all custom code and I still get the error. Fresh template from the Remix repository works fine. I also tried rebuilding my app based on the fresh template (although my current app uses the same server.mjs as in the template). 

```
TypeError: __vite_ssr_import_4__.default is not a function
    at handleRequest (/Users/XXX/web/node_modules/@remix-run/dev/dist/config/defaults/entry.server.node.tsx:18:10)
    at handleDocumentRequestRR (/Users/XXX/web/node_modules/@remix-run/server-runtime/dist/server.js:251:20)
    at async requestHandler (/Users/XXX/web/node_modules/@remix-run/server-runtime/dist/server.js:105:18)
    at async /Users/XXX/web/node_modules/@remix-run/express/dist/server.js:41:22
```

**Comment by ivosabev** [comment]
Figured it was related to the upgrading the `isbot` version to 4+

This line causes the error 

https://github.com/remix-run/remix/blob/0196a1c40df9ecf0d8b1e8133c3136c84401e9cf/packages/remix-dev/config/defaults/entry.server.node.tsx#L6

It should be `import {isbot} from 'isbot';`

**Comment by ivosabev** [comment]
Same as https://github.com/remix-run/remix/issues/8434
