### PR TITLE
docs: import from @remix-run/node instead of remix

### PR DESCRIPTION
**Pull request by machour**
Got a `createCookie() is not a function` today after upgrading my app to 1.3.3

According to https://github.com/remix-run/remix/issues/2503#issuecomment-1079963155, we should not import from `remix` or `@remix-run/server-runtime` anymore.

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
This should still be possible if you're not using PNPM/Yarn P'n'P, since the only recommended import has always been from the `remix` package with the `magicExports`.
For people using PNPM/Yarn P'n'P, it was indeed said to use `@remix-run/server-runtime` as an escape hatch.

However, that package (along with all other packages) was never meant to be a public (non-breaking) API.
This has changed since #2359 was released, but  the `remix` package is still backwards compatible.

Once @pcattori & I are finished with #2430, we'll also run the codemod on our `examples` & have a script ready to run the codemod on our docs too.

I think it's best to back off this PR for now, so we keep our docs consistent.

**Comment by machour** [comment]
Ok.....
