### ISSUE TITLE
import_jsx_dev_runtime.jsxDEV is not a function after upgrade to 1.7.0 in Docker Container

### ISSUE THREAD

**Issue by mattoni** [remix-run/remix#4081]
### What version of Remix are you using?

1.7.0

### Steps to Reproduce

After upgrading to 1.7.0 and building my docker container, Going to any page yields `import_jsx_dev_runtime.jsxDEV is not a function` on the server, and an error page is rendered.

Here is my Docker file that causes it to fail:
```
# Base Node image
FROM node:lts-alpine as base

# Setup all node_modules
FROM base as deps

RUN mkdir /app
WORKDIR /app

ADD package.json ./
ADD yarn.lock ./
RUN yarn install --production=false

# Setup production node_modules
FROM base as production-deps

RUN mkdir /app
WORKDIR /app

COPY --from=deps /app/node_modules /app/node_modules
ADD package*.json ./

# Build the app
FROM base as build

ENV NODE_ENV=production

RUN mkdir /app
WORKDIR /app

COPY --from=deps /app/node_modules /app/node_modules

ADD . .
RUN yarn run build

# Build production image
FROM base

RUN mkdir /app
WORKDIR /app

COPY --from=production-deps /app/node_modules /app/node_modules

COPY --from=build /app/build /app/build
COPY --from=build /app/public /app/public
ADD . .

EXPOSE 3000

CMD ["yarn", "start"]
```

It is only failing in the container, running the app even with remix-serve works correctly. All package.json dependencies are locked in.

### Expected Behavior

The app should work as it did before the upgrade to 1.7.0 (Release notes said no changes to code necessary).

### Actual Behavior

The app fails to render any pages.

**Comment by jfstn** [comment]
I came across this issue today while updating `remix`.
It seems to be related to the changes introduced in #3860.
For now, I'm keeping `@remix/dev` on version `1.6.8` and using the other `@remix/*` dependencies on version `1.7.0`

**Comment by mcansh** [comment]
i haven’t seen this in any of my testing thus far, i might be able to take a look tomorrow, but for sure on Monday.

**Comment by mcansh** [comment]
i can't reproduce :(

https://github.com/mcansh/simple-docker-test

**Comment by mcansh** [comment]
ok, i did get this, but on 1.6.8 oddly enough 

![image](https://user-images.githubusercontent.com/11698668/187032010-3b6b5812-4387-49ae-996e-0c36dd917246.jpeg)

**Comment by jfstn** [comment]
I was able to do it locally, as in `remix build` and then `remix start`. I'll make sure that I'll run a clean build tomorrow or monday.

**Comment by chrisvariety** [comment]
Not sure why, but this reproduces handily on a stock [blues stack](https://github.com/remix-run/blues-stack) while running `npm run test:e2e:run`. Normal `npm run dev` does _not_ reproduce it. 

Repro steps are:

```
npx create-remix --template remix-run/blues-stack (answer yes to everything, select TypeScript)
npm run docker
npm run setup
npm run build
npm run test:e2e:run
```

**Comment by jonschlinkert** [comment]
We're getting a similar error with `1.7.0`. I haven't looked at the code in 1.7.0 vs 1.6.8 but it seems that `RemixServer` is exported differently in 1.7.0 than in 1.6.8. 

```js
import { RemixServer } from '@remix-run/react';
console.log(RemixServer) //=> undefined
```

In 1.6.8, `RemixServer` is a function.

This is the error we're getting:

```
Remix App Server started at http://localhost:3000 (http://192.168.1.122:3000)
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at entry.server.tsx:18.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
 ...
```

**Comment by FlatMapIO** [comment]
> We're getting a similar error with `1.7.0`. I haven't looked at the code in 1.7.0 vs 1.6.8 but it seems that `RemixServer` is exported differently in 1.7.0 than in 1.6.8.
> 
> ```js
> import { RemixServer } from '@remix-run/react';
> console.log(RemixServer) //=> undefined
> ```
> 
> In 1.6.8, `RemixServer` is a function.
> 
> This is the error we're getting:
> 
> ```
> Remix App Server started at http://localhost:3000 (http://192.168.1.122:3000)
> Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check your code at entry.server.tsx:18.
> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
>  ...
> ```

The cause of the problem has been found: https://github.com/remix-run/remix/issues/4080#issuecomment-1229356069

**Comment by jfstn** [comment]
@FlatMapIO the problem does not seem to be precisely the same. I tried all those solutions and they don't seem to work.

**Comment by CanRau** [comment]
Hmm weird I'm sure I upgraded couple of days ago and just now ran into this issue 🤨
Also experimenting on another project I briefly ran into it, but resolved it by changing a custom transform stream

Downgrading to 1.6.8 seems to have solved it for now

**Comment by davidlukerice** [comment]
Odd. I also ran into this today when starting up my local dev server for the first time in a few days. Been on 1.7.0 for a while now, though. So not sure what's changed.

**Comment by jfstn** [comment]
Just tried a clean build, with a clean package manager and docker cache. The problem is still there for me.

**Comment by mcansh** [comment]
> Just tried a clean build, with a clean package manager and docker cache. The problem is still there for me. 

is your repo public? or can you try to reproduce on a fresh `npx create-remix@1.6.8`?

**Comment by CanRau** [comment]
Uh to clarify to me it happened running dev on my machine, so no Docker required 😅

But since last time it didn't happen again 🤷🏻‍♂️

**Comment by jfstn** [comment]
> > Just tried a clean build, with a clean package manager and docker cache. The problem is still there for me.
> 
> is your repo public? or can you try to reproduce on a fresh `npx create-remix@1.6.8`?

This only happens with `remix-run/dev` 1.7.0

**Comment by chrisvariety** [comment]
> > Just tried a clean build, with a clean package manager and docker cache. The problem is still there for me.
> 
> is your repo public? or can you try to reproduce on a fresh `npx create-remix@1.6.8`?

public repo reproduction steps are here https://github.com/remix-run/remix/issues/4081#issuecomment-1229538116 (as mentioned, doesn't repro on 1.6.8)

**Comment by dusty** [comment]
I'm having a similar problem, getting an error `TypeError: (0 , import_react.useFetcher) is not a function\n` that I'm seeing in the ErrorBoundary.  

However, I am having a really hard time reproducing it on a minimal repro.   Also, tried clearing out node_modules, cache, build, etc..  My app works fine on 1.6.8, not on 1.7.0.

**Comment by wladiston** [comment]
This is not particular to the @remix-run/dev. I'm experiencing the same issue on my **vercel** environment as well.

Vercel:
![Screen Shot 2022-09-12 at 4 13 56 PM](https://user-images.githubusercontent.com/1843792/189736696-b6649944-05aa-43fe-94ba-1ca0e8f17a0b.png)

Local: 
<img width="805" alt="Screen Shot 2022-09-12 at 4 15 44 PM" src="https://user-images.githubusercontent.com/1843792/189736962-9e4271ff-ec77-477d-b179-d09752aac840.png">

**Comment by InTheCloudDan** [comment]
I'm getting it when deploying to fly.io. Local dev appears to be working fine, as soon as I deployed it app stopped loading and this is in the logs:

```2022-09-13T10:20:03.887 app[2d96f538] ewr [info] TypeError: (0 , import_jsx_dev_runtime.jsxDEV) is not a function
2022-09-13T10:20:03.887 app[2d96f538] ewr [info] at handleRequest (/app/app/entry.server.tsx:23:9)
2022-09-13T10:20:03.887 app[2d96f538] ewr [info] at handleDocumentRequest (/app/node_modules/@remix-run/server-runtime/dist/server.js:409:20)
2022-09-13T10:20:03.887 app[2d96f538] ewr [info] at requestHandler (/app/node_modules/@remix-run/server-runtime/dist/server.js:49:18)
2022-09-13T10:20:03.887 app[2d96f538] ewr [info] at /app/node_modules/@remix-run/express/dist/server.js:39:22
```

**Comment by eseyfert** [comment]
Ran into the same issue. Runs without issues locally, but then end up seeing the `import_jsx_dev_runtime.jsxDEV is not a function` error in our Cypress tests GitHub workflows. Reverting to `@remix-run/dev@1.6.8` fixed that issue, so something is up.

**Comment by arnemolland** [comment]
This is blocking us from upgrading our production apps as well; runs fine on local machines but the production builds running in containers are all encountering this on >1.7.0. Happens both the default express-based Remix App Server and deno runtimes.

**Comment by krivaten** [comment]
> I'm getting it when deploying to fly.io. Local dev appears to be working fine, as soon as I deployed it app stopped loading and this is in the logs:
> 
> ```
> 2022-09-13T10:20:03.887 app[2d96f538] ewr [info] at handleRequest (/app/app/entry.server.tsx:23:9)
> 2022-09-13T10:20:03.887 app[2d96f538] ewr [info] at handleDocumentRequest (/app/node_modules/@remix-run/server-runtime/dist/server.js:409:20)
> 2022-09-13T10:20:03.887 app[2d96f538] ewr [info] at requestHandler (/app/node_modules/@remix-run/server-runtime/dist/server.js:49:18)
> 2022-09-13T10:20:03.887 app[2d96f538] ewr [info] at /app/node_modules/@remix-run/express/dist/server.js:39:22
> ```

Same thing here. I'm able to reproduce it running `remix-serve build` locally as well.

**Comment by mcansh** [comment]
@dusty @wladiston both of your issues are an upstream issue with esbuild (which has since been fixed) https://github.com/evanw/esbuild/issues/2534 - i'll be looking into upgrading our dependency next week

**Comment by dusty** [comment]
Thanks for the followup @mcansh .  We recently tried out 1.7.2 while moving all the keys above spreads and all is well for us.

**Comment by krivaten** [comment]
Thanks @mcansh. Using an `npm-shrinkwrap.json` I've confirmed that updating esbuild to `0.14.50` resolves the problem.

**Comment by egorpavlikhin** [comment]
Adding `remix build` before running the app worked for me:

```
"dev": "remix build && run-p dev:*",
"dev:node": "cross-env NODE_ENV=development nodemon ./server.js --watch ./server.js",
"dev:remix": "npm run clean && npm run partytown && remix watch",
```

**Comment by arnemolland** [comment]
We managed to fix the issue by forcing esbuild to ^0.15.8 (resolutions field in package.json). Now running remix 1.7.2.

**Comment by mcansh** [comment]
> We managed to fix the issue by forcing esbuild to ^0.15.8 (resolutions field in package.json). Now running remix 1.7.2.

nice, I'm actively working on updating our esbuild dep, but we're usually a little weary to do so as it's < v1. they recently added first party support for yarn pnp, which i've personally never used so want to make sure we don't cause any (more) issues after updating :)

**Comment by joelazar** [comment]
I also came across this issue today but in a slightly different format.

I've built with `NODE_ENV=development` env, but when I tried to execute the built server with `NODE_ENV=production`, it failed with the same issue mentioned in the description.

Reverting `@remix-run/dev` to `1.6.8` solves this.

**Comment by jgentes** [comment]
I'm seeing this with `1.7.2`, however if I run `remix build` before `remix-serve` it starts up. 

Then if I run `remix dev`, it will cause my next `remix-serve` to throw the `TypeError: (0 , import_jsx_dev_runtime.jsxDEV) is not a function` error until I run `remix build` again.

**Comment by mcansh** [comment]
ah okay, it just clicked for me that we do enable `jsxDev` in development builds so this is "kind of" expected - opened https://github.com/remix-run/remix/pull/4358 for discussion as well as a fix

**Comment by kemicofa** [comment]
Seeing the same thing in 1.7.6

**Comment by lildesert** [comment]
Hi!
Do we have an ETA on when [this PR](https://github.com/remix-run/remix/pull/4358) will be merged?
My cypress tests run in dev but fail in CI because of this (with `NODE_ENV=test`).

**Comment by xargr** [comment]
I got the same `TypeError: (0 , import_jsx_dev_runtime.jsxDEV) is not a function` with version `1.8.2`

**Comment by lanzoninicola** [comment]
I don't know if it is helpful, but I experienced the same error and solved it in this mode:

- make sure you don't copy the "builds" folders to the container, adding the relevant paths to the `.dockerignore` file:

```
build
public/build
```

- also copy the `package-lock.json` file to ensure that the same versions of the packages used in the development environment are installed. The command in the `Dockerfile`:

`ADD package.json package-lock.json ./`

**Comment by brandonpsmith** [comment]
same 😞 

<img width="877" alt="Screen Shot 2022-12-12 at 1 22 42 AM" src="https://user-images.githubusercontent.com/2806503/206984876-32811b97-22ab-4a57-9e54-ee6814ac26c9.png">

**Comment by mcansh** [comment]
> same 😞
> 
> <img alt="Screen Shot 2022-12-12 at 1 22 42 AM" width="877" src="https://user-images.githubusercontent.com/2806503/206984876-32811b97-22ab-4a57-9e54-ee6814ac26c9.png">

looks like it built with `development` mode, remix-serve will force set `NODE_ENV=production` so `import_jsx_dev_runtime.jsxDEV` won't exist, instead it would need to be `import_jsx_dev_runtime.jsx` i'd check to see if you have a lingering `NODE_ENV` in your shell setup

**Comment by brandonpsmith** [comment]
>  i'd check to see if you have a lingering `NODE_ENV` in your shell setup

Yep. That was my issue. Lingering env. @xargr make sure you do not have `NODE_ENV` set to `development` when you run build. Build with `NODE_ENV=production` then `npm start`. Thank you @mcansh

**Comment by maranomynet** [comment]
Is there a good reason why `remix-serve` hard-codes `NODE_ENV=production`?

`production` mode sounds like a reasonable default, but would it hurt to allow us to explicitly set it to different values (for whatever reason?)

Asking because I have/had reasons, and then things just stopped working once I upgraded from version `1.6.*`

**Comment by jdold07** [comment]
I'm getting this error now after upgrading to 1.12.0.  No docker, this is macos dev env.  Upgraded and setup to run new dev env with concurrent TW, remix dev & nodemon:

`concurrently \"npm run dev:css\" \"remix dev\" \"nodemon ./server.js\"`

Everything builds, but I get this same error of

`TypeError: (0 , import_jsx_dev_runtime.jsxDEV) is not a function`

Only way I can actually get project to render without error now is to run:

```
npm run build
npm run start
```
This at least allows me to still view the project.

I've tried 

1. removing build/**/*, public/build/**/*, .cache/**/* and rebuilding.
2. removing package-lock.json and running npm i -f
3. removing node_modules/**/* && package-lock.json and running npm i
4. All of the above with <LiveReload /> in root.tsx && the same commented out

The error still occurs.  Essentially I can no longer use npm run dev, I need to build and start to view project.

**Comment by cjbland** [comment]
For what it's worth, I'm using 1.13.0 and I ran into this issue when I was explicitly setting `NODE_ENV` to something other than "production". Specifically running something like this: `NODE_ENV="development" npm run build && npm run start`. The console looks like this for me:

```
$> NODE_ENV="development" npm run build

> build
> npm run build:css && remix build


> build:css
> tailwindcss -o ./app/tailwind.css


Rebuilding...

Done in 340ms.
Building Remix app in development mode...
Built in 671ms
$> npm start
Remix App Server started at http://localhost:3000 (http://192.168.3.60:3000)
TypeError: (0 , import_jsx_dev_runtime.jsxDEV) is not a function
    at handleRequest (/myproject/build/index.js:50:55)
    at handleDocumentRequestRR (/myproject/node_modules/@remix-run/server-runtime/dist/server.js:229:20)
    at requestHandler (/myproject/node_modules/@remix-run/server-runtime/dist/server.js:67:18)
    at /myproject/node_modules/@remix-run/express/dist/server.js:39:22
GET / 500 - - 23.433 ms
```

Changing "development" to "production" and everything works as expected.

**Comment by qianjiachun** [comment]
remix 1.9.0
no docker
Debian GNU/Linux 11 x86_64

I may encounter this problem accidentally. Here is my solution (temporary)

1. Upload the entire source code directory to the server, except for 'build', 'public' and 'node_ modules`
2. `npm i`
3. `npm run build`
4. `npm run start`
5. Delete the source code, leaving only ` build ` ` public ` ` package. json ` ` package-lock. json`
6. Upload the compiled file again in the future, and the webpage will not report errors again


My other servers have never had such problems (upload the build file can run), but this server can't.
I don't know why. It works anyway.😂



here is my package.json
```
{
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "run-s build:*",
    "build:css": "npm run generate:css -- --minify",
    "build:remix": "remix build",
    "dev": "run-p dev:*",
    "dev:css": "npm run generate:css -- --watch",
    "dev:remix": "remix dev",
    "generate:css": "npx tailwindcss -i ./styles/tailwind.css -o ./app/styles/tailwind.css",
    "dev:sass": "sass --no-source-map --style compressed --watch styles/:app/styles/",
    "build:sass": "sass --no-source-map --style compressed styles/:app/styles/",
    "start": "export PORT=7003 && remix-serve build",
    "lint:eslint": "eslint --cache --max-warnings 0 \"app/**/*.{vue,js,ts,tsx}\" --fix",
    "lint:prettier": "prettier --write  \"app/**/*.{js,ts,json,tsx,css,less,scss,vue,html,md}\"",
    "lint": "npm run lint:eslint && npm run lint:prettier",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@ant-design/icons": "^4.8.0",
    "@remix-run/node": "^1.9.0",
    "@remix-run/react": "^1.9.0",
    "@remix-run/serve": "^1.9.0",
    "@types/nprogress": "^0.2.0",
    "@typescript-eslint/eslint-plugin": "^5.47.0",
    "@typescript-eslint/parser": "^5.47.0",
    "@uiw/react-watermark": "^0.0.5",
    "antd": "^4.24.3",
    "await-to-js": "^3.0.0",
    "axios": "^1.2.1",
    "browserlist": "^1.0.1",
    "clsx": "^1.2.1",
    "copy-to-clipboard": "^3.3.3",
    "dayjs": "^1.11.7",
    "echarts-stat": "^1.2.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.31.11",
    "immer": "^9.0.16",
    "npm-check": "^6.0.1",
    "nprogress": "^0.2.0",
    "prettier": "^2.8.1",
    "pure-md5": "^0.1.14",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-google-recaptcha-v3": "^1.10.1",
    "ulid": "^2.3.0",
    "use-immer": "^0.8.1"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.9.0",
    "@remix-run/eslint-config": "^1.9.0",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "concurrently": "^7.6.0",
    "eslint": "^8.30.0",
    "npm-run-all": "^4.1.5",
    "patch-package": "^6.5.0",
    "sass": "^1.57.1",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.9.4"
  },
  "engines": {
    "node": ">=14"
  }
}
```

**Comment by eran-or** [comment]
For me this issue happened after uninstall packages some packages.
npm install then npm run dev fixed the issue.

**Comment by kyeotic** [comment]
I'm running into this as well, but can recreate it without docker. However, if I build with `NODE_ENV=production` and run _without_ that flag I don't hit the `jsxDEV is not a function` error, instead I hit this LiveReload error (which makes sense, it thinks we are in dev)

```
Warning: Expected server HTML to contain a matching <script> in <body>.
script
LiveReload2@http://localhost:3000/build/_shared/chunk-ZVKXYPQ3.js:7712:59
body
html
Root
RemixRoute@http://localhost:3000/build/_shared/chunk-ZVKXYPQ3.js:6987:20
RenderedRoute@http://localhost:3000/build/_shared/chunk-ZVKXYPQ3.js:4475:7
RenderErrorBoundary@http://localhost:3000/build/_shared/chunk-ZVKXYPQ3.js:4831:9
Routes@http://localhost:3000/build/_shared/chunk-ZVKXYPQ3.js:4706:7
Router@http://localhost:3000/build/_shared/chunk-ZVKXYPQ3.js:4657:7
RouterProvider@http://localhost:3000/build/_shared/chunk-ZVKXYPQ3.js:4604:7
RemixErrorBoundary@http://localhost:3000/build/_shared/chunk-ZVKXYPQ3.js:6604:5
RemixBrowser@http://localhost:3000/build/_shared/chunk-ZVKXYPQ3.js:8147:55
```

Either way, it seems building for production is still broken. Seems like the [PR fix](https://github.com/remix-run/remix/pull/4358) has stalled.

**Comment by VerioN1** [comment]
I am using the latest remix (1.14.3) on docker.
same error, didn't change the NODE_ENV from 'production' .
![image](https://user-images.githubusercontent.com/15872957/226279319-17760911-8ec9-4898-becf-27b5c379b5ad.png)

**Comment by lukaszdz** [comment]
I'm getting the same error when I deploy it to fly.io and visit the deployed app. Happens on a fresh remix install and deploy of this PWA remix stack - https://github.com/ShafSpecs/rockspec-stack

```
I'm not sure if this is related, but I'm getting the same error when I deploy it to fly.io. Happens on a fresh install and fresh deploy of this PWA remix stack - https://github.com/ShafSpecs/rockspec-stack

$ fly logs -a my-app-staging

Waiting for logs...

2023-03-29T21:12:49.233 runner[8a81e785] sjc [info] Starting instance
2023-03-29T21:12:49.354 runner[8a81e785] sjc [info] Configuring virtual machine
2023-03-29T21:12:49.356 runner[8a81e785] sjc [info] Pulling container image
2023-03-29T21:12:54.625 runner[8a81e785] sjc [info] Unpacking image
2023-03-29T21:13:01.167 runner[8a81e785] sjc [info] Preparing kernel init
2023-03-29T21:13:01.545 runner[8a81e785] sjc [info] Configuring firecracker
2023-03-29T21:13:02.342 runner[8a81e785] sjc [info] Starting virtual machine
2023-03-29T21:13:02.655 app[8a81e785] sjc [info] Starting init (commit: 8e03fa6)...
2023-03-29T21:13:02.680 app[8a81e785] sjc [info] Preparing to run: `docker-entrypoint.sh npm run start` as root
2023-03-29T21:13:02.706 app[8a81e785] sjc [info] 2023/03/29 21:13:02 listening on [fdaa:0:44ae:a7b:b2e2:8a81:e785:2]:22 (DNS: [fdaa::3]:53)
2023-03-29T21:13:03.453 app[8a81e785] sjc [info] > start
2023-03-29T21:13:03.453 app[8a81e785] sjc [info] > remix-serve build
2023-03-29T21:13:04.297 health[8a81e785] sjc [warn] Health check on port 8080 is in a 'warning' state. Your app may not be responding properly. Services exposed on ports [80, 443] may have intermittent failures until the health check passes.
2023-03-29T21:13:04.424 app[8a81e785] sjc [info] Remix App Server started at http://localhost:8080 (http://172.19.70.138:8080)
2023-03-29T21:13:10.060 health[8a81e785] sjc [info] Health check on port 8080 is now passing.
2023-03-29T21:23:54.660 app[8a81e785] sjc [info] TypeError: (0 , import_jsx_dev_runtime.jsxDEV) is not a function
2023-03-29T21:23:54.660 app[8a81e785] sjc [info] at handleRequest (/app/app/entry.server.tsx:13:5)
2023-03-29T21:23:54.660 app[8a81e785] sjc [info] at handleDocumentRequestRR (/app/node_modules/@remix-run/server-runtime/dist/server.js:229:20)
2023-03-29T21:23:54.660 app[8a81e785] sjc [info] at requestHandler (/app/node_modules/@remix-run/server-runtime/dist/server.js:67:18)
2023-03-29T21:23:54.660 app[8a81e785] sjc [info] at /app/node_modules/@remix-run/express/dist/server.js:39:22
2023-03-29T21:23:54.667 app[8a81e785] sjc [info] GET / 500 - - 69.908 ms
2023-03-29T21:23:58.762 app[8a81e785] sjc [info] TypeError: (0 , import_jsx_dev_runtime.jsxDEV) is not a function
2023-03-29T21:23:58.762 app[8a81e785] sjc [info] at handleRequest (/app/app/entry.server.tsx:13:5)
2023-03-29T21:23:58.762 app[8a81e785] sjc [info] at handleDocumentRequestRR (/app/node_modules/@remix-run/server-runtime/dist/server.js:229:20)
2023-03-29T21:23:58.762 app[8a81e785] sjc [info] at requestHandler (/app/node_modules/@remix-run/server-runtime/dist/server.js:67:18)
2023-03-29T21:23:58.762 app[8a81e785] sjc [info] at /app/node_modules/@remix-run/express/dist/server.js:39:22
2023-03-29T21:23:58.763 app[8a81e785] sjc [info] GET / 500 - - 4.490 ms
```

**Comment by mcansh** [comment]
> I'm getting the same error when I deploy it to fly.io and visit the deployed app. Happens on a fresh remix install and deploy of this PWA remix stack - https://github.com/ShafSpecs/rockspec-stack

@lukaszdz i noticed you have a `.dockerignore` with just `node_modules`, can you try adding `build` and `public/build` to that? in theory running `npm run build` should alleviate that, but perhaps not

**Comment by VerioN1** [comment]
> > I'm getting the same error when I deploy it to fly.io and visit the deployed app. Happens on a fresh remix install and deploy of this PWA remix stack - https://github.com/ShafSpecs/rockspec-stack
> 
> @lukaszdz i noticed you have a `.dockerignore` with just `node_modules`, can you try adding `build` and `public/build` to that? in theory running `npm run build` should alleviate that, but perhaps not

helped to fix !

**Comment by jjenzz** [comment]
this happens out-of-the box with the following steps:

- run `npx create-remix@latest` (1.16.1 at time of writing)
- choose `Just the basics`
- choose `Netlify`
- choose `Typescript`
- choose "yes" to install npm deps
- open project and run `NODE_ENV=production npm run build`
- run `npm run start`

opening browser shows the following:

![Screenshot 2023-05-27 at 21 30 26](https://github.com/remix-run/remix/assets/175330/12a9ad07-aac0-4395-8a92-2e73d940efd0)

<details>
  <summary>server log</summary>
  ```json
  {
      "errorMessage": "lambdaFunc[lambdaHandler] is not a function",
      "errorType": "TypeError",
      "level": "error",
      "stackTrace": [
          "Object._executeSync (/Users/jenna/.nvm/versions/node/v18.7.0/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js:295:47)",
          "/Users/jenna/.nvm/versions/node/v18.7.0/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js:95:26",
          "new Promise (<anonymous>)",
          "Object.execute (/Users/jenna/.nvm/versions/node/v18.7.0/lib/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js:87:16)",
          "Module.invokeFunction (file:///Users/jenna/.nvm/versions/node/v18.7.0/lib/node_modules/netlify-cli/src/lib/functions/runtimes/js/index.mjs:60:36)",
          "NetlifyFunction.invoke (file:///Users/jenna/.nvm/versions/node/v18.7.0/lib/node_modules/netlify-cli/src/lib/functions/netlify-function.mjs:122:41)",
          "processTicksAndRejections (node:internal/process/task_queues:96:5)",
          "handler (file:///Users/jenna/.nvm/versions/node/v18.7.0/lib/node_modules/netlify-cli/src/lib/functions/server.mjs:159:33)"
      ]
  }
  ```
</detail>

**Comment by inssein** [comment]
This is a pretty real problem. I created a brand new remix app, just the basics, served by Remix App Server and using typescript.

`remix run start` doesn't even work without first running `npm run dev`, and the second run I get the error described in this thread.

**Comment by akila-advisory** [comment]
I was able to fix this issue by changing my node version to >16 in package.json.
```
  "engines": {
    "node": ">=16"
  }
```

**Comment by b-goldney** [comment]
I was able to fix this issue by changing my node version to >16 in package.json.

```
  "engines": {
    "node": ">=16"
  }
```

**Comment by MichaelDeBoey** [comment]
#6964 solves this from happening

**Comment by mcansh** [comment]
@yehudamakarov is this locally or on some CI? if locally, try adding `public/build`, `build`, and `.cache` to your `.dockerignore`

**Comment by yehudamakarov** [comment]
@mcansh as of now i'm just testing my container locally, but soon I'll probably set up CI
