### PR TITLE
chore(remix-dev): use fullImportPath to resolve package

### LINKED ISSUE #2691: ESM? Build errors after updating to v1.3.5
### What version of Remix are you using?

1.3.5 and 1.4.0

### Steps to Reproduce

update from 1.3.4 to 1.3.5 or 1.4.0

run `remix build`

### Expected Behavior

App should compile

### Actual Behavior

Lots of errors starting with the following:

```
Building Remix app in production mode...
y-indexeddb is possibly an ESM only package and should be bundled with "serverDependenciesToBundle in remix.config.js.
The path "encoding" is imported in generated/prisma/client/runtime/index.js but encoding is not listed in your package.json dependencies. Did you forget to install it?
✘ [ERROR] [plugin server-bare-modules] Cannot find module 'encoding/package.json'
Require stack:
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/commands.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/run.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli/index.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/index.js
- /node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/cli.js
    generated/prisma/client/runtime/index.js:15389:26:
      15389 │         convert = require("encoding").convert;
            ╵                           ~~~~~~~~~~
  This error came from the "onResolve" callback registered here:
    node_modules/.pnpm/@remix-run+dev@1.3.5_25e4b5bc5190ce64f1c1869d744ce914/node_modules/@remix-run/dev/compiler/plugins/serverBareModulesPlugin.js:46:12:
      46 │       build.onResolve({
         ╵             ~~~~~~~~~
```

There are many more errors, but all seem realeted.

Reverting back to v1.3.4 and everything is ok again.

### PR DESCRIPTION
**Pull request by mcansh**
some packages like `@heroicons/react` use a subdirectory package.json for things, like `@heroicons/react/solid`

closes #2691

Signed-off-by: Logan McAnsh <logan@mcan.sh>

Closes: #

- [ ] Docs
- [ ] Tests

### CODE REVIEW

File: packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts [hunk 1]
```diff
@@ -68,7 +68,6 @@ export function serverBareModulesPlugin(
           onWarning &&
           !isNodeBuiltIn(packageName) &&
           !/\bnode_modules\b/.test(importer) &&
-          !builtinModules.includes(packageName) &&
```
Comment (mcansh) [inline packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts:71]: `isNodeBuiltIn` just calls `builtinModules.includes(packageName)`

**Review by jacob-ebey — APPROVED** [review]
