### ISSUE TITLE
isbot v4 breaking change in templates and hidden files

### ISSUE THREAD

**Issue by alexanderson1993** [remix-run/remix#8407]
### Reproduction

- Run `npx create-remix@latest` with all default options
- Delete `entry.server.ts`
- Run `npm remove isbot`
- Run `npm install` to make sure the dependency is removed from `node_modules`
- Run `npm run dev`

It will print the following and add `"isbot": "latest"` to `package.json`:

```
adding `isbot` to your package.json, you should commit this change
```

- The app should fail to build.

**Note: As of this issue being filed, it appears a new version has been marked as `latest`, so the breaking v4 version is no longer installed. As such, the reproduction doesn't break anything. However, the breaking v4 version will be marked as `latest` soon.**

If you want to break it now, run `npm install isbot@next` to install the new `isbot@4`.

https://www.npmjs.com/package/isbot#version-4-will-become-the-latest-version-on-npm-on-january-2024

### System Info

```shell
System:
    OS: macOS 13.6.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 31.58 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.volta/tools/image/node/18.18.2/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.8.1 - ~/.volta/tools/image/node/18.18.2/bin/npm
    pnpm: 8.6.10 - ~/.volta/bin/pnpm
    bun: 1.0.11 - ~/.bun/bin/bun
    Watchman: 2023.11.20.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.0
  npmPackages:
    @remix-run/css-bundle: ^2.4.1 => 2.4.1 
    @remix-run/dev: ^2.4.1 => 2.4.1 
    @remix-run/node: ^2.4.1 => 2.4.1 
    @remix-run/react: ^2.4.1 => 2.4.1 
    @remix-run/serve: ^2.4.1 => 2.4.1
```

### Used Package Manager

npm

### Expected Behavior

The dev server should build and start up without issue.

### Actual Behavior

The app fails to build with an invalid import error.

**Comment by alexanderson1993** [comment]
It seems `isbot` is the only dependency that's handled this way. It seems possible there will be breaking changes in the future, but the maintainer seems to be following semver, so it might be a good idea to use a major pinned version instead of "latest".

**Comment by brophdawg11** [comment]
This is resolved by #8385 and will be available in the next release.  To workaround the issue in the meantime, you can downgrade `isbot` to `3.x` in your `package.json`

**Comment by brophdawg11** [comment]
This is now being handled by https://github.com/remix-run/remix/pull/8415 - but will still be available in the next release

**Comment by omrilotan** [comment]
I have released [isbot@3.8.0](https://github.com/omrilotan/isbot/pull/234) (`isbot@legacy`) to help with the migration. This version includes isbot.isbot property and a named property.

With v3.8.0 users will be able to import the "isbot" property using the same syntax as a named import

```js
import { isbot } from "isbot" // works on >=3.8.0, >=4.0.0
```

**Comment by jarimustonen** [comment]
For me, the added line is `"isbot": "latest"`.

And running `remix dev --manual` gives the following:

```
[remix-serve] http://localhost:3000 (http://192.168.0.109:3000)

TypeError: (0 , import_isbot.default) is not a function
    at handleRequest (/Users/jari/Sources/okv-homepage/homepage-fi/node_modules/@remix-run/dev/dist/config/defaults/entry.server.node.tsx:18:10)
    at handleDocumentRequestRR (/Users/jari/Sources/okv-homepage/homepage-fi/node_modules/@remix-run/server-runtime/dist/server.js:224:18)
    at requestHandler (/Users/jari/Sources/okv-homepage/homepage-fi/node_modules/@remix-run/server-runtime/dist/server.js:105:18)
    at /Users/jari/Sources/okv-homepage/homepage-fi/node_modules/@remix-run/express/dist/server.js:41:22
TypeError: (0 , import_isbot.default) is not a function
    at handleRequest (/Users/jari/Sources/okv-homepage/homepage-fi/node_modules/@remix-run/dev/dist/config/defaults/entry.server.node.tsx:18:10)
    at handleDocumentRequestRR (/Users/jari/Sources/okv-homepage/homepage-fi/node_modules/@remix-run/server-runtime/dist/server.js:251:20)
    at requestHandler (/Users/jari/Sources/okv-homepage/homepage-fi/node_modules/@remix-run/server-runtime/dist/server.js:105:18)
    at /Users/jari/Sources/okv-homepage/homepage-fi/node_modules/@remix-run/express/dist/server.js:41:22
GET / 500 - - 15.194 ms
```

I fixed this by changing the version requirement to be specific: `"isbot": "3.8.0"`

**Comment by brophdawg11** [comment]
Resolved via #8415
