### ISSUE TITLE
useLoader has TS circular reference errors

### ISSUE THREAD

**Issue by rjspencer** [remix-run/remix#6734]
### What version of Remix are you using?

1.18.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Types worked correctly in v1.16.1, the error appeared when updating to v1.18.0. I believe the Prisma type is causing the issue as loaders without Prisma responses do not have type issues.

The app was built from the Indie Stack with Prisma v4.14.1 and Postgres. No recent migrations. I tried upgrading Prisma and re-running `npx prisma generate`. Neither helped.

```
export async function loader({ request }: { request: Request }) {

  const data = await getDataFromPrisma();

  return json({ data });
}

export default function Index() {
  const { data } = useLoader<typeof loader>() 
  ...
}

Discord conversation pointed to possible place where the issue lives: https://github.com/remix-run/remix/blob/1c416b0b9baadbd75974ee72efb651b8186670cb/packages/remix-server-runtime/serialize.ts#L34
Link to Discord discussion: https://discord.com/channels/770287896669978684/1123658553782173738/1123658553782173738

### Expected Behavior

`useLoader<typeof loader>()` correctly infers the type from the loader return. 

### Actual Behavior

Typescript error on the `useLoader` line.

```
error TS2615: Type of property 'product' circularly references itself in mapped type 'SerializeObject<UndefinedToOptional<Price>>'.

69   const { organizationSubscription } = useLoaderData<typeof loader>();
```

**Comment by pcattori** [comment]
Duplicate of #6701
