### ISSUE TITLE
Vercel deploy fails with an errors

### ISSUE THREAD

**Issue by KostarSf** [remix-run/remix#5803]
### What version of Remix are you using?

1.14.2

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

npx create-remix@latest remix-app or yarn create remix remix-app
Just the basics
Vercel
TypeScript

cd remix-app
npm install or yarn 
vercel build or vercel deploy

### Expected Behavior

App should deploy or build successfully via Vercel CLI or Vercel website

### Actual Behavior

App build crashed with the following errors:

When deploying on Vercel with `vercel deploy` or from GitHub repo import (log from Deployment Status):
```
Error: EISDIR: illegal operation on a directory, unlink '/vercel/path0/node_modules/@remix-run/dev'
02:56:41.372 | BUILD_FAILED: EISDIR: illegal operation on a directory, unlink '/vercel/path0/node_modules/@remix-run/dev'
```

When using `vercel build` in PowerShell on Windows 10:
```
Error: EPERM: operation not permitted, symlink 'C:\Users\kosta\AppData\Roaming\npm\node_modules\vercel\node_modules\@remix-run\dev' -> 'C:\Users\kosta\repos\remix-app-kostar\node_modules\@remix-run\dev'
```

And there is a different error that appeared on deploy in my other repo:
```
...
03:20:14.982 | $ remix build
03:20:15.928 | Building Remix app in production mode...
03:20:16.995 |  
03:20:16.996 | ✘ [ERROR] Could not resolve "@remix-run/react"
03:20:16.996 |  
03:20:16.997 | ../../var/task/node_modules/@remix-run/dev/dist/config/defaults/entry.client.react.tsx:1:29:
03:20:16.997 | 1 │ import { RemixBrowser } from "@remix-run/react";
03:20:16.997 | ╵                              ~~~~~~~~~~~~~~~~~~
03:20:16.997 |  
03:20:16.997 | You can mark the path "@remix-run/react" as external to exclude it from the bundle, which will remove this error.
03:20:16.997 |  
03:20:16.997 | ✘ [ERROR] Could not resolve "react"
03:20:16.997 |  
03:20:16.997 | ../../var/task/node_modules/@remix-run/dev/dist/config/defaults/entry.client.react.tsx:2:44:
03:20:16.997 | 2 │ import { startTransition, StrictMode } from "react";
03:20:16.998 | ╵                                             ~~~~~~~
03:20:16.998 |  
03:20:16.998 | You can mark the path "react" as external to exclude it from the bundle, which will remove this error.
03:20:16.998 |  
03:20:16.998 | ✘ [ERROR] Could not resolve "react-dom/client"
...
[03:20:16.999] Build failed with 4 errors:
[03:20:17.000] ../../var/task/node_modules/@remix-run/dev/dist/config/defaults/entry.client.react.tsx:1:29: ERROR: Could not resolve "@remix-run/react"
[03:20:17.000] ../../var/task/node_modules/@remix-run/dev/dist/config/defaults/entry.client.react.tsx:2:44: ERROR: Could not resolve "react"
[03:20:17.000] ../../var/task/node_modules/@remix-run/dev/dist/config/defaults/entry.client.react.tsx:3:28: ERROR: Could not resolve "react-dom/client"
[03:20:17.000] ../../var/task/node_modules/@remix-run/dev/dist/config/defaults/entry.client.react.tsx:10:8: ERROR: Could not resolve "react/jsx-runtime"
[03:20:17.000] Error
[03:20:17.000]     at Object.onCompileFailure (/var/task/node_modules/@remix-run/dev/dist/cli/commands.js:193:13)
[03:20:17.000]     at Object.compile (/var/task/node_modules/@remix-run/dev/dist/compiler/remixCompiler.js:40:134)
[03:20:17.000]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[03:20:17.001]     at async Object.build (/var/task/node_modules/@remix-run/dev/dist/compiler/build.js:33:3)
[03:20:17.001]     at async Object.build (/var/task/node_modules/@remix-run/dev/dist/cli/commands.js:188:3)
[03:20:17.001]     at async Object.run (/var/task/node_modules/@remix-run/dev/dist/cli/run.js:456:7)
[03:20:17.012] fatal error: all goroutines are asleep - deadlock!
...
[03:20:17.048] ERROR: "build:remix" exited with 1.
[03:20:17.059] error Command failed with exit code 1.
[03:20:17.060] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[03:20:17.079] Error: Command "yarn run build" exited with 1
[03:20:17.454] BUILD_FAILED: Command "yarn run build" exited with 1
```

The `remix dev` command works well everywhere

**Comment by itsMapleLeaf** [comment]
This happened after I removed my `entry.client.tsx` and `entry.server.tsx` files. It seems like `@remix-run/dev` needs to declare some missing deps

**Comment by andrecasal** [comment]
After upgrading Remix to v1.14.0 and deleting `entry.server.ts` and `entry.client.ts`, builds fine locally, but I'm getting this error on Vercel:

```console
✘ [ERROR] Could not resolve "@remix-run/react"
--
22:21:34.423 |  
22:21:34.423 | ../../var/task/node_modules/@remix-run/dev/dist/config/defaults/entry.client.react.tsx:1:29:
22:21:34.423 | 1 │ import { RemixBrowser } from "@remix-run/react";
22:21:34.423 | ╵                              ~~~~~~~~~~~~~~~~~~
22:21:34.423 |  
22:21:34.424 | You can mark the path "@remix-run/react" as external to exclude it from the bundle, which will remove this error.
```

Adding the entry.client.tsx and entry.server.tsx files back in solved the issue 🎉

Here are the files if you need them:

`entry.client.tsx`
```ts
import { RemixBrowser } from '@remix-run/react'
import { startTransition, StrictMode } from 'react'
import { hydrateRoot } from 'react-dom/client'

const hydrate = () => {
	startTransition(() => {
		hydrateRoot(
			document,
			<StrictMode>
				<RemixBrowser />
			</StrictMode>
		)
	})
}

if (typeof requestIdleCallback === 'function') {
	requestIdleCallback(hydrate)
} else {
	// Safari doesn't support requestIdleCallback
	// https://caniuse.com/requestidlecallback
	setTimeout(hydrate, 1)
}
```

`entry.server.ts
```ts
import type { EntryContext } from '@remix-run/node'
import { RemixServer } from '@remix-run/react'
import { renderToString } from 'react-dom/server'

export const handleRequest = (request: Request, responseStatusCode: number, responseHeaders: Headers, remixContext: EntryContext) => {
	const markup = renderToString(<RemixServer context={remixContext} url={request.url} />)

	responseHeaders.set('Content-Type', 'text/html')

	return new Response('<!DOCTYPE html>' + markup, {
		headers: responseHeaders,
		status: responseStatusCode,
	})
}

export default handleRequest
```

**Comment by KostarSf** [comment]
Yes, Vercel deploys successfully with these files, thanks

**Comment by brophdawg11** [comment]
Sounds like this is resolved?  I didn't have any issues building a fresh app choosing the vercel template
