### ISSUE TITLE
Unable to "npm run build" remix app after upgrading to 1.8.0

### ISSUE THREAD

**Issue by saudpunjwani101** [remix-run/remix#4764]
### What version of Remix are you using?

1.8.0

### Steps to Reproduce

1 - Create new remix app by using "npx create-remix@latest"
2 - Choose where to create the application (app directory)
3 - Select any template. I selected the basic Remix app server
4 - Choose Ts or Js
5 - Run "npm install" inside the app directory
6 - Run "npm run dev" and go to the browser to see the app running in development but instead see the error "Error: Cannot find module '/Users/saud/git/new-remix-app/build/index.js'"
7 - Okay so it requires a build. Do "npm run build" and you get the errors,
app/entry.client.tsx:1:29: ERROR: Could not resolve "@remix-run/react"
app/entry.client.tsx:3:28: ERROR: Could not resolve "react-dom/client"
app/root.tsx:9:7: ERROR: Could not resolve "@remix-run/react"

### Expected Behavior

The app should build so we can run it in dev mode.

### Actual Behavior

It's throwing an error on "npm run build".

Full cli logs:

Building Remix app in production mode...

✘ [ERROR] Could not resolve "@remix-run/react"

    app/entry.client.tsx:1:29:
      1 │ import { RemixBrowser } from "@remix-run/react";
        ╵                              ~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@remix-run/react" here because it'snot listed as a dependency of this package:

    ../.pnp.cjs:73:33:
      73 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "@remix-run/react" as external to exclude it from the bundle, which will remove this error.

 ✘ [ERROR] Could not resolve "react-dom/client"

    app/entry.client.tsx:3:28:
      3 │ import { hydrateRoot } from "react-dom/client";
        ╵                             ~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "react-dom" here because it's not listed as a dependency of this package:

    ../.pnp.cjs:73:33:
      73 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "react-dom/client" as external to exclude it from the bundle, which will remove this error.

 ✘ [ERROR] Could not resolve "@remix-run/react"

    app/root.tsx:9:7:
      9 │ } from "@remix-run/react";
        ╵        ~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@remix-run/react" here because it'snot listed as a dependency of this package:

    ../.pnp.cjs:73:33:
      73 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "@remix-run/react" as external to exclude it from the bundle, which will remove this error.

Build failed with 3 errors:
app/entry.client.tsx:1:29: ERROR: Could not resolve "@remix-run/react"
app/entry.client.tsx:3:28: ERROR: Could not resolve "react-dom/client"
app/root.tsx:9:7: ERROR: Could not resolve "@remix-run/react"
Error
    at Object.onCompileFailure (/Users/saud/git/new-remix-app/node_modules/@remix-run/dev/dist/cli/commands.js:174:13)
    at Object.compile (/Users/saud/git/new-remix-app/node_modules/@remix-run/dev/dist/compiler/remixCompiler.js:33:134)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.build (/Users/saud/git/new-remix-app/node_modules/@remix-run/dev/dist/compiler/build.js:33:3)
    at async Object.build (/Users/saud/git/new-remix-app/node_modules/@remix-run/dev/dist/cli/commands.js:169:3)
    at async Object.run (/Users/saud/git/new-remix-app/node_modules/@remix-run/dev/dist/cli/run.js:448:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `remix build`
npm ERR! Exit status 1

**Comment by machour** [comment]
Hi, and thank you for filing this issue.

If I follow your reproduction steps and it works. At step 6, simply running `npm run dev` starts the app correctly.

I see later that you're mentioning Yarn PnP, how come?

Could you please elaborate on your setup and provide the full installation log? Here's mine:

```
🍺  ~ $ npx create-remix@latest
Need to install the following packages:
  create-remix@latest
Ok to proceed? (y) y
? Where would you like to create your app? bug-4764
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. Remix App Server
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

added 1054 packages, and audited 1055 packages in 1m

229 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
💿 That's it! `cd` into "/Users/didou/bug-4764" and check the README for development and deploy instructions!
🍺  ~ $ cd bug-4764/
🍺  ~/bug-4764 $ ls
README.md         app               node_modules      package-lock.json package.json      public            remix.config.js   remix.env.d.ts    tsconfig.json
🍺  ~/bug-4764 $ yar
🍺  ~/bug-4764 $ npm run dev

> dev
> remix dev

Remix App Server started at http://localhost:3000 (http://192.168.1.6:3000)
```

**Comment by saudpunjwani101** [comment]
Yes I noticed the logs it's using yarn. I have no idea why it's using Yarn plug n play while I created the app using npm. So doing "yarn install" fixes the issue. Anyway, it's a problem with my machine and not with remix. Sorry for the trouble.
