### ISSUE TITLE
[VITE] isBot crashes the server in 2.4.1 if isbot is over v4

### ISSUE THREAD

**Issue by ZeldOcarina** [remix-run/remix#8392]
### Reproduction

https://stackblitz.com/edit/remix-run-remix-vwrwea

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 198.97 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    bun: 1.0.3 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.2.1
  npmPackages:
    @remix-run/dev: ^2.4.1 => 2.4.1 
    @remix-run/eslint-config: ^2.4.1 => 2.4.1 
    @remix-run/express: ^2.4.1 => 2.4.1 
    @remix-run/node: ^2.4.1 => 2.4.1 
    @remix-run/react: ^2.4.1 => 2.4.1 
    vite: ^5.0.10 => 5.0.10
```

### Used Package Manager

npm

### Expected Behavior

Server should start with isbot since it's being used as part of entry.server.ts.

### Actual Behavior

`isbot` is being used in `entry.server.ts`, when upgrading to 2.4.1 and using:

```js
app.all(
  "*",
  createRequestHandler({
    // @ts-expect-error
    build: viteDevServer
      ? () => viteDevServer.ssrLoadModule("virtual:remix/server-build")
      : await import("./build/server/index.js"),
  }),
);
```

server won't start and crashes with àTypeError: __vite_ssr_import_4__.default is not a function`

**Comment by ZeldOcarina** [comment]
Fix is simple:

![image](https://github.com/remix-run/remix/assets/42982095/d3b001cc-7ee0-4ca8-ba28-3bb6d6500bc7)

It just took half an hour to debug, maybe you want to update ìsbot`dependency to latest version and adjust the starter? If it has already been done, sorry for this and pls disregard.

**Comment by michaeldebetaz** [comment]
Thanks for the fix ! Undofortunately, the expected type seems to have changed for the `isbot` function. In `entry.server.tsx`, `request.headers.get()` returns `string` or `null`, but `isbot()` expects `string`
```ts
export default function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext,
) { 
  return isbot(request.headers.get("user-agent") ?? "") // Add ?? "" to fix the type error. Hopefully it doesn't break anything
    ? handleBotRequest(
        request,
...
```

**Comment by brophdawg11** [comment]
This is resolved by #8385 - you can install `isbot@3` in your `package.json` for now to use with the internal entry.* files.

**Comment by brophdawg11** [comment]
Resolved by #8385 and will be available in the next release

**Comment by ZeldOcarina** [comment]
nah it's fine I've handled the dependancy import manually!
